# Generated by Django 5.1.3 on 2024-11-28 06:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("merchant", "商家"),
                            ("customer", "客人"),
                            ("admin", "管理員"),
                            ("staff", "服務人員"),
                        ],
                        default="customer",
                        help_text="用戶角色，例如商家、客人、管理員等",
                        max_length=10,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="用戶的聯絡電話，例如手機號碼", max_length=15, null=True
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="用戶頭像，存儲圖片文件的路徑",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="用戶創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="用戶資料的最後更新時間"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="RoleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="分類名稱，例如 '技術類' 或 '管理類'", max_length=50),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="分類的描述，例如該分類適用於哪些角色", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="分類是否啟用，預設為啟用狀態"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="該分類的創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="該分類的最後更新時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="創建人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_role_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="最後修改人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_role_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="店鋪名稱，例如 '幸福剪髮'", max_length=150)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="店鋪的具體地址", max_length=255, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="店鋪的聯絡電話", max_length=20, null=True
                    ),
                ),
                ("opening_time", models.TimeField(help_text="店鋪營業的開始時間，例如 '09:00'")),
                ("closing_time", models.TimeField(help_text="店鋪營業的結束時間，例如 '18:00'")),
                (
                    "business_days",
                    models.JSONField(
                        default=list,
                        help_text="店鋪的營業日（JSON格式，例如 ['Monday', 'Tuesday'])",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="店鋪是否啟用，預設為啟用狀態"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="店鋪的創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="店鋪的最後更新時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="創建人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        help_text="店鋪所屬的商家，用戶角色必須是 '商家'",
                        limit_choices_to={"role": "merchant"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="最後修改人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("merchant", "name")},
            },
        ),
        migrations.CreateModel(
            name="StaffRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="角色名稱，例如 '按摩師'", max_length=50)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="角色的描述，例如工作內容或技能要求", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="角色是否啟用，預設為啟用狀態"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="該角色的創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="該角色的最後更新時間"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="角色的分類，例如 '技術類'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.rolecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="創建人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_staff_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="最後修改人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_staff_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="該角色所屬的店鋪",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="服務人員的姓名", max_length=150)),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="服務人員的聯絡電話", max_length=15, null=True
                    ),
                ),
                (
                    "expertise",
                    models.TextField(
                        blank=True, help_text="服務人員的專長描述，例如 '擅長足底按摩'", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="服務人員是否仍在職，預設為在職狀態"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="服務人員的創建時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="服務人員的最後更新時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="創建人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="最後修改人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_account",
                    models.OneToOneField(
                        blank=True,
                        help_text="服務人員對應的用戶帳號（可選）",
                        limit_choices_to={"role": "staff"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="服務人員的角色，例如 '按摩師'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.staffrole",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="服務人員所屬的店鋪",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.store",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rolecategory",
            name="store",
            field=models.ForeignKey(
                help_text="該分類所屬的店鋪",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.store",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="related_store",
            field=models.ForeignKey(
                blank=True,
                help_text="服務人員或管理員所關聯的店鋪（可選）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_users",
                to="users.store",
            ),
        ),
    ]
