# Generated by Django 5.1.3 on 2024-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="related_store",
        ),
        migrations.AddField(
            model_name="user",
            name="related_stores",
            field=models.ManyToManyField(
                blank=True,
                help_text="服務人員或管理員所關聯的多個店鋪",
                related_name="store_users",
                to="users.store",
            ),
        ),
    ]
