# Generated by Django 5.1.3 on 2024-12-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="分類名稱，例如 '技術類' 或 '管理類'", max_length=50),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="分類的描述，例如該分類適用於哪些角色", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="分類是否啟用，預設為啟用狀態"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="該分類的創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="該分類的最後更新時間"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="服務名稱，例如 '男生剪髮'", max_length=150)),
                (
                    "description",
                    models.TextField(blank=True, help_text="服務的詳細描述", null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="服務價格", max_digits=10
                    ),
                ),
                ("duration", models.IntegerField(help_text="服務時長（分鐘）")),
                ("is_active", models.BooleanField(default=True, help_text="服務是否啟用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="創建時間"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="最後修改時間")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="分類名稱，例如 '剪髮'", max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, help_text="分類描述", null=True),
                ),
                ("is_active", models.BooleanField(default=True, help_text="分類是否啟用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="創建時間"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="最後修改時間")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="服務人員的姓名", max_length=150)),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="服務人員的聯絡電話", max_length=15, null=True
                    ),
                ),
                (
                    "expertise",
                    models.TextField(
                        blank=True, help_text="服務人員的專長描述，例如 '擅長足底按摩'", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="服務人員是否仍在職，預設為在職狀態"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="服務人員的創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="服務人員的最後更新時間"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="角色名稱，例如 '按摩師'", max_length=50)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="角色的描述，例如工作內容或技能要求", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="角色是否啟用，預設為啟用狀態"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="該角色的創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="該角色的最後更新時間"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="店鋪名稱，例如 '幸福剪髮'", max_length=150)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="店鋪的具體地址", max_length=255, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="店鋪的聯絡電話", max_length=20, null=True
                    ),
                ),
                ("opening_time", models.TimeField(help_text="店鋪營業的開始時間，例如 '09:00'")),
                ("closing_time", models.TimeField(help_text="店鋪營業的結束時間，例如 '18:00'")),
                (
                    "business_days",
                    models.JSONField(
                        default=list,
                        help_text="店鋪的營業日（JSON格式，例如 ['Monday', 'Tuesday'])",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="店鋪是否啟用，預設為啟用狀態"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="店鋪的創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="店鋪的最後更新時間"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="時段開始時間")),
                ("end_time", models.DateTimeField(help_text="時段結束時間")),
                ("max_capacity", models.IntegerField(default=1, help_text="時段最大預約人數")),
                ("is_active", models.BooleanField(default=True, help_text="時段是否有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="創建時間"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="最後修改時間")),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="排班日期")),
                ("start_time", models.TimeField(help_text="排班開始時間")),
                ("end_time", models.TimeField(help_text="排班結束時間")),
                ("is_active", models.BooleanField(default=True, help_text="排班是否啟用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="創建時間"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="最後修改時間")),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
    ]
