# Generated by Django 5.1.3 on 2024-11-28 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="分類名稱，例如 '剪髮'", max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, help_text="分類描述", null=True),
                ),
                ("is_active", models.BooleanField(default=True, help_text="分類是否啟用")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="創建時間"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="最後修改時間")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="創建人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_service_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="所屬店鋪",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.store",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="最後修改人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_service_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("store", "name")},
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="服務名稱，例如 '男生剪髮'", max_length=150)),
                (
                    "description",
                    models.TextField(blank=True, help_text="服務的詳細描述", null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="服務價格", max_digits=10
                    ),
                ),
                ("duration", models.IntegerField(help_text="服務時長（分鐘）")),
                ("is_active", models.BooleanField(default=True, help_text="服務是否啟用")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="創建時間"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="最後修改時間")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="創建人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        help_text="可以提供該服務的服務人員",
                        related_name="services",
                        to="users.staff",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="服務所屬的店鋪",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.store",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="最後修改人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="服務分類",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("store", "name")},
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="排班日期")),
                ("start_time", models.TimeField(help_text="排班開始時間")),
                ("end_time", models.TimeField(help_text="排班結束時間")),
                ("is_active", models.BooleanField(default=True, help_text="排班是否啟用")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="創建時間"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="最後修改時間")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="創建人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_work_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        help_text="服務人員",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.staff",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="最後修改人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_work_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="時段開始時間")),
                ("end_time", models.DateTimeField(help_text="時段結束時間")),
                ("max_capacity", models.IntegerField(default=1, help_text="時段最大預約人數")),
                ("is_active", models.BooleanField(default=True, help_text="時段是否有效")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="創建時間"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="最後修改時間")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="創建人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_time_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="時段對應的服務",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="最後修改人員",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_time_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        help_text="所屬排班",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.workschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
