# Generated by Django 5.1.3 on 2024-11-28 06:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待確認"),
                            ("confirmed", "已確認"),
                            ("canceled", "已取消"),
                            ("missed", "未出席"),
                        ],
                        default="pending",
                        help_text="預約狀態，例如待確認、已確認、已取消或未出席",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="客人在預約時提交的備註或特殊要求", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="預約創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="預約最後修改時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="記錄創建此預約的用戶",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="關聯到預約的客人，用戶角色必須是 '客人'",
                        limit_choices_to={"role": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="關聯到預約的服務，例如剪髮、按摩等",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        help_text="關聯到提供服務的服務人員",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.staff",
                    ),
                ),
                (
                    "timeslot",
                    models.OneToOneField(
                        help_text="關聯到具體的預約時間段",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="services.timeslot",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="記錄最後修改此預約的用戶",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppointmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待確認"),
                            ("confirmed", "已確認"),
                            ("canceled", "已取消"),
                            ("missed", "未出席"),
                        ],
                        help_text="預約變更後的狀態",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="狀態更新時間"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        help_text="關聯到對應的預約",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="進行狀態變更的用戶",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="評分（1-5）",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="評分不能低於 1 分"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, message="評分不能高於 5 分"
                            ),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="評價內容，例如對服務的反饋", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="評價創建時間"),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        help_text="關聯到對應的預約",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="通知的具體內容")),
                ("is_read", models.BooleanField(default=False, help_text="通知是否已讀")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="通知創建時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="接收通知的用戶",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
