# Generated by Django 5.1.3 on 2024-12-09 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="記錄創建此預約的用戶",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="customer",
            field=models.ForeignKey(
                help_text="關聯到預約的客人",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                help_text="關聯到預約的服務，例如剪髮、按摩等",
                on_delete=django.db.models.deletion.CASCADE,
                to="store.service",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="staff",
            field=models.ForeignKey(
                help_text="關聯到提供服務的服務人員",
                on_delete=django.db.models.deletion.CASCADE,
                to="store.staff",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="timeslot",
            field=models.OneToOneField(
                help_text="關聯到具體的預約時間段",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="store.timeslot",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="記錄最後修改此預約的用戶",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointmenthistory",
            name="appointment",
            field=models.ForeignKey(
                help_text="關聯到對應的預約",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmenthistory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="進行狀態變更的用戶",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="appointment",
            field=models.OneToOneField(
                help_text="關聯到對應的預約",
                on_delete=django.db.models.deletion.CASCADE,
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                help_text="接收通知的用戶",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
